'use server'

import * as cheerio from 'cheerio'
import OpenAI from 'openai'
import { createClient } from '@/lib/supabase/server'
import { getServerUser } from '@/lib/auth/server-user'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

export async function analyzeCompanyUrl(url: string) {
  try {
    const response = await fetch(url)
    if (!response.ok) {
      throw new Error(`Failed to fetch URL: ${response.statusText}`)
    }
    
    const html = await response.text()
    const $ = cheerio.load(html)
    
    // Remove unnecessary tags
    $('script, style, noscript, nav, footer, iframe, svg, img').remove()
    
    let text = $('body').text()
    // Trim extra whitespaces and newlines
    text = text.replace(/\s+/g, ' ').trim()
    
    // Limit to 10000 characters to avoid exceeding token limits
    if (text.length > 10000) {
      text = text.substring(0, 10000)
    }

    const completion = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: '与えられたWebサイトのテキスト情報を元に、会社情報を抽出してください。無い情報は空文字を返してください。事業内容は魅力的になるように最大300文字程度で要約してください。'
        },
        {
          role: 'user',
          content: `以下のテキストから会社情報を抽出して:\n\n${text}`
        }
      ],
      response_format: {
        type: 'json_schema',
        json_schema: {
          name: 'company_info_schema',
          strict: true,
          schema: {
            type: 'object',
            properties: {
              companyName: {
                type: 'string',
                description: '会社名'
              },
              businessDescription: {
                type: 'string',
                description: '事業内容を300文字程度で魅力的に要約'
              },
              missionVision: {
                type: 'string',
                description: '理念やビジョン'
              },
              cultureAndBenefits: {
                type: 'string',
                description: '社風、働く環境、福利厚生など抽出できる範囲で'
              }
            },
            required: ['companyName', 'businessDescription', 'missionVision', 'cultureAndBenefits'],
            additionalProperties: false
          }
        }
      }
    })

    const resultString = completion.choices[0].message.content
    if (!resultString) {
      throw new Error('No output generated by AI.')
    }
    
    const resultObj = JSON.parse(resultString)
    return { success: true, data: resultObj }
    
  } catch (error) {
    console.error('Error analyzing company URL:', error)
    return { success: false, error: error instanceof Error ? error.message : String(error) }
  }
}

export async function saveCompanyProfile(data: {
  companyName: string
  businessDescription: string
  missionVision: string
  cultureAndBenefits: string
}) {
  const serverUser = await getServerUser()
  if (!serverUser || !serverUser.tenant_id) {
    throw new Error('テナント情報が見つかりません。')
  }

  const supabase = await createClient()

  const { error } = await supabase
    .from('tenants')
    .update({
      company_name: data.companyName,
      business_description: data.businessDescription,
      mission_vision: data.missionVision,
      culture_and_benefits: data.cultureAndBenefits,
      onboarding_completed_at: new Date().toISOString(),
    })
    .eq('id', serverUser.tenant_id)

  if (error) {
    console.error('Update tenant profile error:', error)
    throw new Error('会社プロフィールの保存に失敗しました。')
  }

  // 修正: サーバーアクション内での redirect は NEXT_REDIRECT エラーを引き起こすことがあるため
  // クライアント側に success を返して、クライアント側で遷移させます。
  return { success: true }
}
